### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by IlyaSkriblovsky** [SirAnthony/slpp#14]
I'm planning to use SLPP in my project for parsing tables from Lua source files. Meantime, I'm preparing my project for transition to Python 3.

As I can see from #12, you still intentionally support ancient Python 2.4. Supporting both Py2.4 and Py3 in same codebase doesn't seems viable.

Whether Py2.4 support is the requirement for SLPP? Would you welcome if I will port SLPP to support Py2.7 and Py3 by the same code?

Of course, I could just copy slpp.py into my project and make required modifications. I'm just curious if your are interested in my pull requests for py3 support.

**Comment by SirAnthony** [comment]
I do not care about python2.4, I thought that such obsolete versions were dead before I was born, until someone provided pr for it. I prefer to have support for py3, than python<2.6

**Comment by IlyaSkriblovsky** [comment]
That's great. I already have a branch with py3 support, but it depends on both #16 and #17 that are still waiting for your attention. If you will accept them, I will make another PR with py3 support.
