### ISSUE TITLE
No unicode encoding

### ISSUE THREAD

**Issue by embryo10** [SirAnthony/slpp#22]
While I can decode lua objects with unicode characters ok, when I try to encode a dictionary like this
```python
{1: 'testing', 2: {'unicode value': 'κείμενο', 'int value': 456123}}
```
I get a `UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 1: ordinal not in range(128)` error
Any fix for this?

**Comment by SirAnthony** [comment]
Fixed after #19
