### ISSUE TITLE
Can't import.

### ISSUE THREAD

**Issue by A2C2A-1** [SirAnthony/slpp#25]
**My OS: Arch linux**
**Python version: 3.8.0**
I installed slpp with the following command:
```pip3 install git+https://github.com/SirAnthony/slpp```
When I try to **import** a module, the following error appears:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/slpp.py", line 132
    print ERRORS['unexp_end_string']
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(ERRORS['unexp_end_string'])?
```

**Comment by A2C2A-1** [comment]
Oh, this is only for python2... Why is it not written in the description?

**Comment by etcher-be** [comment]
@A2C2A-1 there's a fork with Py3 support [here](https://github.com/IlyaSkriblovsky/slpp-23).
