### ISSUE TITLE
Splits strings containing dash (minus symbol)

### ISSUE THREAD

**Issue by amarvin** [SirAnthony/slpp#30]
For example, I think `{name = first-name}` is acceptable LUA data structure format.

```python
>>> from slpp import slpp
>>> dump = '{name = first-name}'
>>> slpp.decode(dump)
Malformed number (no digits after initial minus).
{'name': 'first', 1: 'name'}
```

**Comment by amarvin** [comment]
Regex can be used as a quick-fix to add quotes around hyphenated strings:

```python
>>> import re
>>> from slpp import slpp
>>> dump = '{name = first-name}'
>>> slpp.decode(dump)
Malformed number (no digits after initial minus).
{'name': 'first', 1: 'name'}
>>> dump = re.sub(r'\w+(?:-\w+)+', r'"\g<0>"', dump)
>>> slpp.decode(dump)
{'name': 'first-name'}
```

**Comment by SirAnthony** [comment]
Please clarify, since it is result in error in interpreter.
```lua
> a = {name = first-name}
stdin:1: attempt to perform arithmetic on global 'first' (a nil value)
stack traceback:
    stdin:1: in main chunk
```

**Comment by amarvin** [comment]
Might be the LUA data structure formatted file that I needed to parse was incorrectly formatted, but it had a few values like this.

**Comment by SirAnthony** [comment]
If you mean data like [recipes from issue repo you mentioned](https://github.com/simpsus/factoriograph/blob/master/res/recipe_0.18.19.txt), it does not seem as valid lua format, more like some custom parser used for it.

**Comment by amarvin** [comment]
Yep, that's the one.
