### ISSUE TITLE
decode bug : missing last zero in lua array

### ISSUE THREAD

**Issue by enjolras1205** [SirAnthony/slpp#8]
from slpp import slpp as lua
print(lua.decode({0,1,0}))
set([0, 1])
should be set([0, 1, 0])

I comment line in slpp.py:154
#if k:
the last zero is not missing now.

what's the purpose of this line?

**Comment by SirAnthony** [comment]
Thanks.

**Comment by enjolras1205** [comment]
thanks for reply.
: )
